enum CategoryMedicinalPlant {
  adesmiaBijuga('Adesmia bijuga', 'adesmia_bijuga',
      'Adesmia bijuga es una especie de planta fanerógama de la familia Fabaceae.'),
  alliumSativumGarlic('Allium sativum (Garlic)', 'allium_sativum',
      'El ajo (Allium sativum) es una planta perenne, herbácea y bulbosa que puede alcanzar más de 60 cm de altura.'),
  altamiza('Altamiza', 'altamiza',
      'La altamisa es una planta herbácea anual que pertenece a la familia de las compuestas.'),
  amaranto('Amaranto', 'amaranto',
      'El amaranto es una planta herbácea anual que puede alcanzar hasta 3 metros de altura.'),
  ballotaAcetabulosa('Ballota acetabulosa', 'ballota_acetabulosa',
      'Ballota acetabulosa es una especie de planta herbácea perteneciente a la familia de las lamiáceas.'),
  blumeaBalsamifera('Blumea balsamifera', 'blumea_balsamifera',
      'Blumea balsamifera es una especie de planta fanerógama de la familia Asteraceae.'),
  calahuala('Calahuala', 'calahuala',
      'La calahuala es una planta herbácea perenne que pertenece a la familia de las polipodiáceas.'),
  carneHumana('Carne humana', 'carne_humana',
      'La planta Carne humana es una especie de planta fanerógama de la familia Aristolochiaceae.'),
  cedron('Cedron', 'cedron',
      'El cedrón es una planta herbácea perenne que pertenece a la familia de las verbenáceas.'),
  chilpetin('Chilpetin', 'chilpetin',
      'El chilpetín es una planta que pertenece a la familia de las solanáceas.'),
  chimpu('Chimpu', 'chimpu',
      'El chimpu es una planta que pertenece a la familia de las solanáceas.'),
  chulco('Chulco', 'chulco',
      'El chulco es una planta que pertenece a la familia de las solanáceas.'),
  clavel('Clavel', 'clavel',
      'El clavel es una planta herbácea perenne que pertenece a la familia de las cariofiláceas.'),
  clavelRosaBeso('Clavel Rosa Beso', 'clavel_rosa_beso',
      'El clavel rosa beso es una planta herbácea perenne que pertenece a la familia de las cariofiláceas.'),
  colaCaballo('Cola Caballo', 'cola_caballo',
      'La cola de caballo es una planta perenne que pertenece a la familia de las equisetáceas.'),
  combretumIndicum('Combretum indicum', 'combretum_indicum',
      'Combretum indicum es una especie de planta fanerógama de la familia Combretaceae.'),
  desiertoFourOClock('Desierto Four OClock', 'desierto_four_oclock',
      'La planta Desierto Four OClock es una especie de planta fanerógama de la familia Nyctaginaceae.'),
  diantheraSecunda('Dianthera Secunda', 'dianthera_secunda',
      'Dianthera secunda es una especie de planta fanerógama de la familia Melastomataceae.'),
  dienteLeon('Diente Leon', 'diente_leon',
      'El diente de león es una planta herbácea perenne que pertenece a la familia de las asteráceas.'),
  ehretiaMicrophylla('Ehretia microphylla', 'ehretia_microphylla',
      'Ehretia microphylla es una especie de planta fanerógama de la familia Boraginaceae.'),
  epazote('Epazote', 'epazote',
      'El epazote es una planta herbácea anual que pertenece a la familia de las quenopodiáceas.'),
  hiervaLuisa('Hierva Luisa', 'hierva_luisa',
      'La hierba luisa es una planta herbácea perenne que pertenece a la familia de las verbenáceas.'),
  higo('Higo', 'higo',
      'El higo es una planta arbórea que pertenece a la familia de las moráceas.'),
  iresineHerbstii('Iresine herbstii', 'iresine_herbstii',
      'Iresine herbstii es una especie de planta fanerógama de la familia Amaranthaceae.'),
  lavandaGoodwin('Lavanda goodwin', 'lavanda_goodwin',
      'La lavanda Goodwin es una planta arbustiva que pertenece a la familia de las lamiáceas.'),
  limaLimon('Lima Limon', 'lima_limon',
      'La lima limón es un árbol frutal que pertenece a la familia de las rutáceas.'),
  llanten('Llánten', 'llanten',
      'El llantén es una planta herbácea perenne que pertenece a la familia de las plantagináceas.'),
  malvaRosa('Malva Rosa', 'malva_rosa',
      'La malva rosa es una planta herbácea perenne que pertenece a la familia de las malváceas.'),
  manzanilla('Manzanilla', 'manzanilla',
      'La manzanilla es una planta herbácea anual que pertenece a la familia de las asteráceas.'),
  menta('Menta', 'menta',
      'La menta es una planta herbácea perenne que pertenece a la familia de las lamiáceas.'),
  mentha('Mentha', 'mentha',
      'La menta es una planta herbácea perenne que pertenece a la familia de las lamiáceas.'),
  momordicaCharantia('Momordica charantia', 'momordica_charantia',
      'Momordica charantia es una especie de planta fanerógama de la familia Cucurbitaceae.'),
  orejaBurro('Oreja Burro', 'oreja_burro',
      'La oreja de burro es una planta herbácea perenne que pertenece a la familia de las asteráceas.'),
  oxalisLatifolia('Oxalis latifolia', 'oxalis_latifolia',
      'Oxalis latifolia es una especie de planta fanerógama de la familia Oxalidaceae.'),
  penaPena('Pena Pena', 'pena_pena',
      'La pena pena es una planta herbácea perenne que pertenece a la familia de las asteráceas.'),
  peperomiaPellucida('Peperomia pellucida', 'peperomia_pellucida',
      'Peperomia pellucida es una especie de planta fanerógama de la familia Piperaceae.'),
  psidiumGuajava('Psidium guajava', 'psidium_guajava',
      'Psidium guajava es una especie de planta fanerógama de la familia Myrtaceae.'),
  romero('Romero', 'romero',
      'El romero es una planta arbustiva que pertenece a la familia de las lamiáceas.'),
  ruda('Ruda', 'ruda',
      'La ruda es una planta arbustiva que pertenece a la familia de las rutáceas.'),
  santaMaria('Santa María', 'santa_maria',
      'La Santa María es una planta herbácea anual que pertenece a la familia de las asteráceas.'),
  sennaAlata('Senna alata', 'senna_alata',
      'Senna alata es una especie de planta fanerógama de la familia Fabaceae.'),
  sabila('Sábila', 'sabila',
      'La sábila es una planta suculenta de la familia Asphodelaceae.'),
  toronjil('Toronjil', 'toronjil',
      'El toronjil es una planta herbácea perenne que pertenece a la familia de las lamiáceas.'),
  vitexNegundo('Vitex negundo', 'vitex_negundo',
      'Vitex negundo es una especie de planta fanerógama de la familia Lamiaceae.'),
  alheli('alhelí', 'alheli',
      'El alhelí es una planta herbácea perenne que pertenece a la familia de las brasicáceas.'),
  canelon('canelon', 'canelon',
      'El canelón es una planta herbácea anual que pertenece a la familia de las solanáceas.'),
  suculenta('suculenta', 'suculenta',
      'Las suculentas son plantas que tienen la capacidad de almacenar agua en sus hojas, tallos y raíces.'),
  nachic('Ñachic', 'ñachic',
      'El ñachic es una planta herbácea anual que pertenece a la familia de las solanáceas.');

  final String _name;
  final String _description;
  final String _image;

  const CategoryMedicinalPlant(this._name, this._image,
      [this._description = '']);

  String get name => _name;
  String get image => _image;
  String get description => _description;

  static CategoryMedicinalPlant categoryByName(String name) {
    for (CategoryMedicinalPlant category in CategoryMedicinalPlant.values) {
      if (category.name == name) {
        return category;
      }
    }
    return CategoryMedicinalPlant.adesmiaBijuga;
  }
}
